system:
  ip: 127.0.0.1
  port: 8080
  gin_mode: debug
redis:
  Addr: 127.0.0.1:6379
  Password: ""
  DB: 0
jwt:
  secret: spigcoderisahandsomeguy
  expire: 3
  issuer: spigcoder
log: 
  app: blog_server
  dir: logs
db:
  host: 127.0.0.1
  port: 3306
  user: root
  password: Tang20050120.
  name: blog_server
  debug: true
  source: mysql
  max_idle_conns: 10
  max_open_conns: 100